### ISSUE TITLE
[createchart] charts aren't created when called from runprofile

### ISSUE THREAD

**Issue by mattackard** [200106-uta-go/project-3#27]
createchart works on its own, but for some reason isn't working when the functions are called in runprofile. None of the directories or files are getting created.

```
panic: open ./charts/profileC/values.yaml: no such file or directory

goroutine 1 [running]:
github.com/200106-uta-go/project-3/pkg/kreate.createValues(0xc000084b50, 0x8, 0xc0000b0680, 0x11, 0xc000084b90, 0x9, 0xc000064640, 0x1, 0x1, 0xc0000bb9d0, ...)
        /home/opensuse/go/src/github.com/200106-uta-go/project-3/pkg/kreate/createchart.go:60 +0x1df
github.com/200106-uta-go/project-3/pkg/kreate.RunProfile(0x7ffc57ae9eed, 0xd, 0x2, 0x2)
        /home/opensuse/go/src/github.com/200106-uta-go/project-3/pkg/kreate/runprofile.go:47 +0x3b6
main.main()
        /home/opensuse/go/src/github.com/200106-uta-go/project-3/cmd/kreate/main.go:51 +0x102
```

**Comment by mattackard** [comment]
will work on it after scrum

**Comment by mattackard** [comment]
swapped individual function calls to just CreateChart and all is good
